### ISSUE TITLE
UnrecoverableScannerException: Could not find project for config file path: null (1.3.0)

### ISSUE THREAD

**Issue by JohT** [jqassistant-plugin/jqassistant-typescript-plugin#148]
The [update to v1.3.0](https://github.com/JohT/code-graph-analysis-pipeline/pull/221) fails with the error message below. There was no problem with [version v1.2.3](https://github.com/JohT/code-graph-analysis-pipeline/actions/runs/10600384544).

```
Error: Exception in thread "main" com.buschmais.jqassistant.core.scanner.impl.UnrecoverableScannerException: Unexpected problem encountered while scanning: item='./source/.reports/jqa/ts-output.json', path='/home/runner/work/code-graph-analysis-pipeline/code-graph-analysis-pipeline/temp/react-router-6.26.1/./source/.reports/jqa/ts-output.json', scope='PROJECT', pipeline='[com.buschmais.jqassistant.plugin.common.impl.scanner.FileResourceScannerPlugin@2db6d68d, org.jqassistant.plugin.typescript.impl.TypescriptProjectScannerPlugin@f723cdb]'. Please report this error including the full stacktrace (continueOnError=false).
	at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:105)
	at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:63)
	at com.buschmais.jqassistant.plugin.common.impl.scanner.FileScannerPlugin.scan(FileScannerPlugin.java:35)
	at com.buschmais.jqassistant.plugin.common.impl.scanner.FileScannerPlugin.scan(FileScannerPlugin.java:21)
	at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:125)
	at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:84)
	at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:63)
	at com.buschmais.jqassistant.commandline.task.ScanTask.scan(ScanTask.java:103)
	at com.buschmais.jqassistant.commandline.task.ScanTask.lambda$scanFiles$4(ScanTask.java:93)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at com.buschmais.jqassistant.commandline.task.ScanTask.scanFiles(ScanTask.java:83)
	at com.buschmais.jqassistant.commandline.task.ScanTask.lambda$run$0(ScanTask.java:61)
	at java.base/java.util.Optional.ifPresentOrElse(Optional.java:196)
	at com.buschmais.jqassistant.commandline.task.ScanTask.lambda$run$2(ScanTask.java:60)
	at com.buschmais.jqassistant.commandline.task.AbstractStoreTask.withStore(AbstractStoreTask.java:50)
	at com.buschmais.jqassistant.commandline.task.ScanTask.run(ScanTask.java:51)
	at com.buschmais.jqassistant.commandline.Main.executeTask(Main.java:320)
	at com.buschmais.jqassistant.commandline.Main.executeTasks(Main.java:278)
	at com.buschmais.jqassistant.commandline.Main.interpretCommandLine(Main.java:204)
	at com.buschmais.jqassistant.commandline.Main.run(Main.java:82)
	at com.buschmais.jqassistant.commandline.Main.main(Main.java:63)
Caused by: java.lang.IllegalStateException: Could not find project for config file path: null
	at org.jqassistant.plugin.typescript.impl.mapper.core.ProjectMapper.map(ProjectMapper.java:89)
	at org.jqassistant.plugin.typescript.impl.mapper.core.TypeScriptScanMapper.map(TypeScriptScanMapper.java:17)
	at org.jqassistant.plugin.typescript.impl.TypescriptProjectScannerPlugin.scan(TypescriptProjectScannerPlugin.java:43)
	at org.jqassistant.plugin.typescript.impl.TypescriptProjectScannerPlugin.scan(TypescriptProjectScannerPlugin.java:20)
	at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:125)
	at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:88)
```

**Comment by SebastianWendorf** [comment]
Have you rescanned the project with the LCE Tool?

**Comment by JohT** [comment]
Yes. This runs basically all from scratch in the pipeline.

**Comment by SebastianWendorf** [comment]
Both versions need to be on 1.3.0 simultaneously to work properly.

**Comment by JohT** [comment]
Sorry for bothering you.

You were right. Combining both updates did the job: https://github.com/JohT/code-graph-analysis-pipeline/pull/222

I hope that my [Renovate packageRule](https://github.com/JohT/code-graph-analysis-pipeline/blob/6dc2022de7ebe305d78e84e3c5706e3a6c6a3eb5/renovate.json#L22) will cover that next time for me.
